<?php

declare(strict_types=1);

namespace SwooleFabric\Http\Middleware;

use SwooleFabric\Http\Request;
use SwooleFabric\Http\Response;
use SwooleFabric\Kernel\Context;

/**
 * Sets correlation_id and request_id on Context.
 *
 * If the caller supplies an X-Correlation-ID header, it's reused;
 * otherwise a new one is generated.
 */
final class CorrelationMiddleware
{
    public function __invoke(Request $request, Response $response, callable $next): void
    {
        // Use incoming correlation ID or the one generated by Context::reset()
        $correlationId = $request->header('x-correlation-id');
        if ($correlationId !== null) {
            Context::setCorrelationId($correlationId);
        }

        // Set response headers for traceability
        $response->header('X-Request-ID', Context::requestId() ?? '');
        $response->header('X-Correlation-ID', Context::correlationId() ?? '');

        $next();
    }
}
